/*********************************************************************
 SANITY CHECK Feb. 2014 - CODE MODIFICATION REQUIRED
 Modify code following instructions below.
 Remove this box once modifications done.
*********************************************************************/

/*********************************************************************
 SANITY CHECK INSTRUCTION: 
 Test method best practices :
   startTest / stopTest ; assert ; test with another profile
 Remove this box once modification done.
*********************************************************************/
/**
 * This class contains unit tests for validating the behavior of AP16Opportunity Apex classes
 * and triggers.
 *   ~ Author          : Fabien TAILLON ~ fabien.taillon@cgi.com 
     ~ Date Created    : 19/02/2013
 */
@isTest
private class AP16Opportunity_TEST 
{
	/* CR-0734 - Not used anymore */
	/*
    static testMethod void AP16Opportunity_TEST() 
    {
        Opportunity opp = UtilityTestMethod.getOpportunity();
        opp.GrossMargin__c = 5;
        
        
        Test.startTest();
        
        insert opp;
        opp.ForecastedGrossMargin__c = 10;
        update opp;
        
        Test.StopTest();
    }
    */
}